services:
  weaviate:
    image: semitechnologies/weaviate:1.21.5
    ports:
      - "8080:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 20
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: /var/lib/weaviate
      DEFAULT_VECTORIZER_MODULE: none
    volumes:
      - ./weaviate_data:/var/lib/weaviate

  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      RUNNING_IN_DOCKER: "true"        # 👈 Add this line
      WEAVIATE_URL: http://weaviate:8080   # Docker internal network hostname
    depends_on:
      - weaviate
